### PR TITLE
Adding helper scripts, reorganizing storage

### PR DESCRIPTION
**Pull request by ddemidov**
This moves device nodes to `./devices`, and creates two helper scripts, `get_devices.py` and `clean_arena.py`, as discussed in #1.

An example workflow:

``` sh
$ ./clean_arena.py 
$ ls arena
ls: cannot access arena: No such file or directory
$ ./get_devices.py touch_sensor:0 infrared_sensor:1
$ find arena/ -maxdepth 2
arena/
arena/lego-sensor
arena/lego-sensor/sensor1
arena/lego-sensor/sensor0
```

pinging @WasabiFan

### CODE REVIEW

**Comment by WasabiFan** [comment]
Mostly looks good. The one issue I see is that I don't think it manages the `address` of the devices it creates. If the device was copied from `in3`, that is how it will show up in the device tree in tests.

I think it needs to take another parameter for input on each device and change the device's address to match. Unfortunately, because addresses can include colons in them, the script will need to intelligently manage the input to only split by the first two colons.

**Comment by ddemidov** [comment]
Yes, forgot about that. Will update the PR.

**Comment by ddemidov** [comment]
@WasabiFan, I can try to add some advanced command line options parser (something like `-d device -i index -a address`), or I can just parse options like `touch_sensor:0@in1` (`@in1` being optional). What do you think?

**Comment by WasabiFan** [comment]
I'd vote for simple. Just pick a character (I like the @ idea) to use, and split by that just like the existing ones. Should be perfect for our needs.

**Comment by WasabiFan** [comment]
So, that means I'm in favor of the latter option in your question.

**Comment by ddemidov** [comment]
Got that :)

**Comment by ddemidov** [comment]
54d3867 does that.

**Comment by WasabiFan** [comment]
Looks good to me -- let's get a look over it from @rhempel so he knows what's happening and can make sure it looks good and then we can get this merged.

**Comment by rhempel** [comment]
@ddemidov, is `get_devices` solid? Would it be better called `create_devices` or `make_devices`?

**Comment by ddemidov** [comment]
Its function is to pull devices from a "device database" into testing arena. So may be `pull_devices`?

**Comment by WasabiFan** [comment]
`populate_device_tree`?

**Comment by ddemidov** [comment]
`test_devices`?

**Comment by WasabiFan** [comment]
My thoughts:

### `create_devices` / `make_devices`

It _is_ creating device nodes, so this makes sense. But the device data is actually being copied from somewhere else, and the creation of the devices isn't what is important: the important bit is that there are now device nodes where you need them.

### `pull_devices`

Makes sense to us, but for potential contributors, "pulling" devices isn't clear. It isn't very descriptive. Also see the comment above on the part of the action that is important.

### `test_devices`

In its current state, it doesn't really test anything -- it does, however, do things with "test devices" so maybe we could prepend a verb there.

### `populate_device_tree`

I like this one because it has a verb indicating what it is doing and a noun specifying what's changing: the device tree is being populated. I think this would make sense to someone trying to understand what this code does at a glance of the calling code.

**Comment by ddemidov** [comment]
It makes sense. I am sleeping right now, but I'll rename to
populate_device_tree tomorrow if you don't come up with something less
mouthful.

**Comment by WasabiFan** [comment]
Yeah, it's pretty long. Maybe shorten it to `populate_devices`. Whatever it is, I don't think it will make too much of a difference :wink:

**Comment by ddemidov** [comment]
populate_arena? goes with clean_arena

**Comment by rhempel** [comment]
:+1: for `populate-arena`

**Comment by WasabiFan** [comment]
> populate_arena? goes with clean_arena

Sounds good

**Comment by ddemidov** [comment]
I've renamed the script and cleaned up the history.

**Pull request merged**
